# Generated by Django 2.2.4 on 2019-08-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
