# Generated by Django 2.2.4 on 2019-08-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_delete_organization'),
        ('organization', '0002_organization_alias_name'),
    ]

    operations = [
    ]
