# Generated by Django 2.2.4 on 2019-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(0, 'گروه اصلی'), (1, 'حساب کل'), (2, 'حساب معین'), (3, 'تفصیلی')]),
        ),
    ]
