# Generated by Django 2.2.4 on 2019-08-06 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20190806_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocument',
            name='dateTime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2019, 8, 6, 7, 52, 4, 328450, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accountDocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='accounting.AccountingDocument'),
        ),
    ]
