# Generated by Django 2.2.4 on 2019-08-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('accounting', '0006_auto_20190806_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocument',
            name='approved',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='approved', to='user_management.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='confirmed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed', to='user_management.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='prepared',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='prepared', to='user_management.UserProfile'),
            preserve_default=False,
        ),
    ]
