# Generated by Django 2.2.4 on 2019-08-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20190806_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingdocument',
            old_name='dateTime',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='accountDocument',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_document',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.AccountingDocument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='approved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_documents', to='user_management.UserProfile'),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='confirmed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_documents', to='user_management.UserProfile'),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='prepared',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_documents', to='user_management.UserProfile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'بدهکار'), (2, 'بستانکار')], default=0),
            preserve_default=False,
        ),
    ]
