# Generated by Django 2.2.4 on 2019-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountingdocument_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[(0, 'گروه اصلی'), (1, 'حساب کل'), (2, 'حساب معین'), (3, 'تفصیلی')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
