# Generated by Django 2.2.4 on 2019-08-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20190811_1257'),
        ('accounting', '0011_auto_20190810_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias_name', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=255, null=True)),
                ('e_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('staff', models.ManyToManyField(related_name='organization', to='user_management.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountingdocument',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='accountingdocument',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='accountingdocument',
            name='prepared',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounting.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounting.Organization'),
            preserve_default=False,
        ),
    ]
