# Generated by Django 2.2.4 on 2019-08-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20190811_1257'),
        ('accounting', '0012_transaction_description'),
    ]

    operations = [
    ]
